# Updates the package cache and upgrades all installed packages.
#
# Example usage:
# ansible-playbook -i inventory update-all.yml
---
- hosts: all
  become: true

  tasks:  
  - name: Update the apt package index and upgrade packages
    apt:
      upgrade: yes
      update_cache: yes
      